TRAINING SUMMARY:
        data_type (-t): energy_random
        model_name (-n): big_DGBaNR
        activation_function (-a): relu
        model_path (-m): ../save_model/big_DGBaNR_sigmoid_energy_random_1280000_32_Adam_mse_loss_5.pt
        save_model (-s): ../save_model/
        data_size (-d): 1280000
        epochs (-e): 1000
        batch_size (-b): 32
        optim_name (-o): Adam
        loss_name (-l): mse_loss
        num_mc (-mc): 5
        lr (-lr): 0.01
        mean_training (-mt): True
        std_training (-st): True
        train_fraction (-f): 0.9
        save_interval (-i): 1
        random_seed (-r): 42
        
Traceback (most recent call last):
  File "training/train_bayesian_model.py", line 217, in <module>
    train_model(**vars(args))
  File "training/train_bayesian_model.py", line 91, in train_model
    train_loader, test_loader = data_gen.generate_dataset(data_size=data_size, batch_size=batch_size, seed=random_seed, device=device)
  File "../DGBaN/datasets/generate_simple_dataset.py", line 243, in generate_dataset
    self.imgs = np.load(imgs_path)
  File "/home/J000000000007/envs/DGBaN/lib64/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '../save_dataset/energy_images_N-32_data_size-1280000_seed-42.npy'
